In [1]:
# from dict
dict_ = {'n_estimators': {'type': 'int', 'default': 10, 'range': [1, 500]},
 'criterion': {'type': 'str', 'default': 'mse', 'values': ['mse', 'mae']},
 'max_features': {'type': 'str',
  'default': 'auto',
  'range': [None, 'auto', 'log2', 'sqrt']},
 'max_depth': {'type': 'int', 'default': None, 'range': [1, 30]},
 'min_samples_split': {'type': 'int', 'default': 2, 'range': [2, 1000]},
 'min_samples_leaf': {'type': 'int', 'default': 1, 'range': [1, 1000]},
 'min_weight_fraction_leaf': {'type': 'float',
  'default': 0.0,
  'range': [0.0, 100.0]},
 'max_leaf_nodes': {'type': 'int', 'default': None},
 'min_impurity_decrease': {'type': 'float',
  'default': 0.0,
  'range': [0.0, 10.0]},
 'bootstrap': {'type': 'bool', 'default': True},
 'oob_score': {'type': 'bool', 'default': False}
}

In [2]:
from btb.tuning import Tunable

In [22]:
tunable = Tunable.from_dict(dict_)

In [23]:
crit = tunable.hyperparams['criterion']

In [24]:
crit.sample(200)

> /home/pacho/Projects/mit/PVBTB/btb/tuning/hyperparams/categorical.py(151)sample()
    149 
    150         import ipdb; ipdb.set_trace()
--> 151         return self.transform(sampled)

ipdb> c


array([[1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1,

In [21]:
def test():
    import ipdb; ipdb.set_trace()
    return crit.transform([['mse'], ['mae']])
    
test()

> <ipython-input-21-9fe6a90da3d4>(3)test()
      2     import ipdb; ipdb.set_trace()
----> 3     return crit.transform([['mse'], ['mae']])
      4 

ipdb> s
--Call--
> /home/pacho/Projects/mit/PVBTB/btb/tuning/hyperparams/base.py(200)transform()
    199 
--> 200     def transform(self, values):
    201         """Transform one or more hyperparameter values.

ipdb> n
> /home/pacho/Projects/mit/PVBTB/btb/tuning/hyperparams/base.py(244)transform()
    243 
--> 244         if not isinstance(values, np.ndarray):
    245             values = np.asarray(values)

ipdb> n
> /home/pacho/Projects/mit/PVBTB/btb/tuning/hyperparams/base.py(245)transform()
    244         if not isinstance(values, np.ndarray):
--> 245             values = np.asarray(values)
    246 

ipdb> n
> /home/pacho/Projects/mit/PVBTB/btb/tuning/hyperparams/base.py(247)transform()
    246 
--> 247         dimensions = len(values.shape)
    248         if dimensions > 2:

ipdb> values
array([['mse'],
       ['mae']], dtype='<U3'

BdbQuit: 

In [14]:
crit.sample(10)

> /home/pacho/Projects/mit/PVBTB/btb/tuning/hyperparams/categorical.py(152)sample()
    150 
    151         import ipdb; ipdb.set_trace()
--> 152         return self.transform(sampled)

ipdb> c


array([[0, 0],
       [2, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [2, 0],
       [0, 0],
       [2, 0]])

In [5]:
tunable.hyperparams['max_features'].choices

[None, 'auto', 'log2', 'sqrt']

In [8]:
tunable.hyperparams['criterion'].sample(10)

array([[1, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [2, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 0]])

In [7]:
tunable.hyperparams['criterion'].inverse_transform(tunable.hyperparams['criterion'].sample(20))

ValueError: Values found outside of the valid range [0, 1]: [2.0, 2.0, 2.0, 2.0, 2.0]

In [73]:
from sklearn.preprocessing import OneHotEncoder

In [183]:
from hashlib import md5

NONE = md5(b'NONE').hexdigest()

In [184]:
NONE

'b50339a10e1de285ac99d4c3990b8693'

In [256]:
choices = np.array(['dog', 'cat', 1, 3, None, np.pi, np.inf])
values = np.array(['dog', 'cat', np.inf], dtype=object) #, 1, 3, None, np.pi])

In [257]:
encoder = OneHotEncoder(categories=[choices], sparse=False)
encoder.fit(choices.reshape(-1, 1))

OneHotEncoder(categorical_features=None,
              categories=[array(['dog', 'cat', 1, 3, None, 3.141592653589793, inf], dtype=object)],
              drop=None, dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=False)

In [258]:
encoder.transform(values.reshape(-1, 1))

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [190]:
rever = encoder.inverse_transform(transf)

In [191]:
rever[rever == NONE] = None

In [192]:
rever

array([['cat'],
       ['dog'],
       ['cat'],
       [None]], dtype=object)

In [68]:
encoder

OneHotEncoder(categorical_features=None,
              categories=[array(['cat', 'adog'], dtype='<U4')], drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=False)

In [69]:
encoder.fit(np.array(['cat', 'adog']).reshape(-1, 1))

ValueError: Unsorted categories are not supported for numerical categories

In [71]:
x = np.array(['cat', 'adog'])
x.sort()

In [72]:
x

array(['adog', 'cat'], dtype='<U4')

In [63]:
encoder.categories_

[array(['cat', 'dog'], dtype='<U3')]

In [52]:
encoder.transform([[None]])

array([[1., 0.]])

In [267]:
%%timeit
for name, hp in tunable.hyperparams.items():
    pass

266 ns ± 1.52 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [268]:
%%timeit
for hp in tunable.hyperparams.values():
    pass

167 ns ± 0.221 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [269]:
tunable.hyperparams.values()

dict_values([<btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d92e64550>, <btb.tuning.hyperparams.categorical.CategoricalHyperParam object at 0x7f1d92e64d68>, <btb.tuning.hyperparams.categorical.CategoricalHyperParam object at 0x7f1d92faf898>, <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d933a3710>, <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d933a3c18>, <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d933a3ba8>, <btb.tuning.hyperparams.numerical.FloatHyperParam object at 0x7f1d933a3ac8>, <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d933a3518>, <btb.tuning.hyperparams.numerical.FloatHyperParam object at 0x7f1d933a3a90>, <btb.tuning.hyperparams.boolean.BooleanHyperParam object at 0x7f1d933a3c50>, <btb.tuning.hyperparams.boolean.BooleanHyperParam object at 0x7f1d933a3b70>])

In [270]:
tunable.hyperparams.items()

dict_items([('n_estimators', <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d92e64550>), ('criterion', <btb.tuning.hyperparams.categorical.CategoricalHyperParam object at 0x7f1d92e64d68>), ('max_features', <btb.tuning.hyperparams.categorical.CategoricalHyperParam object at 0x7f1d92faf898>), ('max_depth', <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d933a3710>), ('min_samples_split', <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d933a3c18>), ('min_samples_leaf', <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d933a3ba8>), ('min_weight_fraction_leaf', <btb.tuning.hyperparams.numerical.FloatHyperParam object at 0x7f1d933a3ac8>), ('max_leaf_nodes', <btb.tuning.hyperparams.numerical.IntHyperParam object at 0x7f1d933a3518>), ('min_impurity_decrease', <btb.tuning.hyperparams.numerical.FloatHyperParam object at 0x7f1d933a3a90>), ('bootstrap', <btb.tuning.hyperparams.boolean.BooleanHyperParam object at 0x7f1d933a3c50>), ('oob_sco

In [274]:
hp = tunable.hyperparams['criterion']

In [288]:
x = hp.sample(12)

In [292]:
hp._encoder

OneHotEncoder(categorical_features=None,
              categories=[array(['mse', 'mae'], dtype=object)], drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=False)

In [307]:
randomized_values = np.random.random((100, 2))
indexes = np.argmax(randomized_values, axis=1)


In [309]:
hp.transform(indexes)

/home/pacho/.virtualenvs/PVBTB/lib/python3.6/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


ValueError: Values found outside of the valid space ['mse', 'mae']: [0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0]

In [310]:
from btb.tuning import CategoricalHyperParam

In [311]:
hpz = CategoricalHyperParam(choices=['mae','mze'])

In [312]:
hpz.sample(10)

array([[0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0]])

In [296]:
hp._encoder.transform(np.array(['mae']).reshape(-1, 1))

array([[1., 0.]])

In [291]:
x

array([[0, 0],
       [1, 0],
       [2, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [2, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0]])

In [290]:
hp.inverse_transform(x)

ValueError: Values found outside of the valid range [0, 1]: [2.0, 2.0]

In [318]:
hp._encoder.

[array(['mse', 'mae'], dtype=object)]

In [278]:
np.add(hp.transform(hp.default))

array([[0, 0]])